name: mobile_optical_reader
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  image_picker: ^1.0.7
  http: ^1.2.1
  firebase_core: ^2.30.0
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.0
  firebase_storage: ^11.7.2
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/